version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: "f1-compose"
    environment:
      - NODE_ENV=production
    ports:
      - "2564:3000"
    command: "npm start"
  q2:
    build: .
    image: "q2-compose"
    ports:
      - "9001:2564"